### ISSUE TITLE
Date picker lists incorrect day of week

### ISSUE THREAD

**Issue by danielsharvey** [andreialecu/ngx-material-luxon#3]
There is a mismatch between Luxon Info weekdays and the 0 == Sunday used
everywhere else in Luxon. The Luxon Info structure lists Monday at index 0.

This mismatch causes the date picker to show incorrect days of the week in the
calendar.

**Comment by danielsharvey** [comment]
Fix proposed in #2

**Comment by andreialecu** [comment]
Thanks for reporting. Should be fixed by #2 and #5 

Published as `1.0.6`
