### ISSUE TITLE
Weekday names shift on use

### ISSUE THREAD

**Issue by oglematt** [andreialecu/ngx-material-luxon#7]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

If you open the mat-datepicker and page through months, the weekday names shift each time. Additionally, if you open the date picker multiple times, the weekday names shift each time.

## Expected behavior

Weekday names should remain consistent.

## Minimal reproduction of the problem with instructions
Install into a clean Angular Material project and use the mat-datepicker.

## Environment

<pre><code>
Angular version: 11.0.9

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by oglematt** [comment]
Pretty easy solve, I think. I made the change and would be happy to submit a PR, but the repo isn't allowing it. At any rate, if you change line 122 to copy the Array, it seems to work as expected. Apparently, Info.weekdays() returns a mutable object.

`
const luxonWeekdays = [...Info.weekdays(style, { locale: this.locale })];
`

**Comment by andreialecu** [comment]
Thanks for reporting, will take a look.

**Comment by oglematt** [comment]
Also, apparently they know it, just hasn't been fixed yet. I don't think copying the array will hurt anything, even if they fix the mutability issue. It's an open issue on the Luxon repo.

moment/luxon#829

**Comment by andreialecu** [comment]
I wasn't really able to reproduce it. But the solution seems valid based on the upstream issue.

Published as `1.1.1`
