### ISSUE TITLE
Angular Material Datepicker set start of week day

### ISSUE THREAD

**Issue by andreacasarella** [andreialecu/ngx-material-luxon#9]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ x ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The mat-datepicker calendar picker shows as initial day of week always Sunday.

## Expected behavior

The mat-datepicker calendar popup should start with Monday as initial day of weeks based on locale.

## Minimal reproduction of the problem with instructions

AppModule
<pre><code>...
registerLocaleData(localeIt);

@NgModule({
...
imports: [
    ...
    SharedModulesModule,
    ...
],
providers: [
    ...
    // provide app locale
    {provide: LOCALE_ID, useValue: 'it-CH'}
]
})
</code></pre>

SharedModulesModule
<pre><code>...
const firstDayOfWeek = () => {
  return getWeekStartByLocale(LOCALE_ID.toString());
}

const MODULES = [
  CommonModule,
  ReactiveFormsModule,
  MaterialModule,
  LuxonDateModule
];

@NgModule({
  imports: MODULES,
  exports: MODULES,
  providers: [
    { provide: DateAdapter, useClass: LuxonDateAdapter, deps: [MAT_DATE_LOCALE] },
    { provide: MAT_DATE_FORMATS, useValue: DateFormats.settings },
    { provide: MAT_LUXON_DATE_ADAPTER_OPTIONS, useValue: { firstDayOfWeek, useUtc: true } }
  ]
})
export class SharedModulesModule { }
</code></pre>

MaterialModule
<pre><code>...
@NgModule({
  exports: [
    ...
    MatLuxonDateModule
  ]
})
export class MaterialModule {
}
</code></pre>

![image](https://user-images.githubusercontent.com/930014/128485419-8481da9d-3ebc-4cbf-bdb5-bb294e224fbe.png)

As you can see the calendar show correctly localized month and days labels but starts with Sunday , D as Domenica in italian. I would like to start with Monday, L as Lunedi in italian. How can I achieve that change based on the fact that getWeekStartByLocale provided by weekstart lib returns correctly (1 = Monday).

Thanks a lot for your help.

## Environment

<pre><code>
Angular version: 11.2.14

Browser:
- [ x ] Chrome (desktop) version 92.0.4515.131
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.16.1  
- Platform:  Windows

Others:

</code></pre>

**Comment by andreialecu** [comment]
```ts
const firstDayOfWeek = (locale) => {
  return getWeekStartByLocale(LOCALE_ID.toString());
}
```

Is this snippet correct? Should it not be `return getWeekStartByLocale(locale);`?

**Comment by andreialecu** [comment]
If you hardcode it to `return 1;` do you see Monday as the first day?

**Comment by andreacasarella** [comment]
> ```ts
> const firstDayOfWeek = (locale) => {
>   return getWeekStartByLocale(LOCALE_ID.toString());
> }
> ```
> 
> Is this snippet correct? Should it not be `return getWeekStartByLocale(locale);`?

Yeah sorry, forget locale param

**Comment by andreacasarella** [comment]
> If you hardcode it to `return 1;` do you see Monday as the first day?

nope

**Comment by andreialecu** [comment]
If you `console.log` something from within that `firstDayOfWeek` function does it log it? Is it being called?

**Comment by andreacasarella** [comment]
> If you `console.log` something from within that `firstDayOfWeek` function does it log it? Is it being called?

Actually nothing is logged...

**Comment by andreialecu** [comment]
Are you sure you're using this library and not the one that was recently merged to angular?

The official one doesn't support `firstDayOfWeek`.

**Comment by andreacasarella** [comment]
I followed the instruction given here: https://github.com/andreialecu/ngx-material-luxon
npm install ngx-material-luxon --save

Where is the official one?

**Comment by andreacasarella** [comment]
Hi there, any news? Could u kindly provide a running stackblitz example?

**Comment by andreacasarella** [comment]
I found the solution:
it was missing the MAT_LUXON_DATE_ADAPTER_OPTIONS in the DateAdapter provider

`{ provide: DateAdapter, useClass: LuxonDateAdapter, deps: [MAT_DATE_LOCALE, MAT_LUXON_DATE_ADAPTER_OPTIONS] }`
